#!/bin/bash

set -e

rm -rf rescript-language-server || true
git clone git@github.com:rescript-lang/rescript-language-server.git

rm -rf vendor || true
mkdir -p vendor/server

cd rescript-language-server
rm -rf server/out || true
npm install
npm run compile
cp package.json ../vendor/
cp package-lock.json ../vendor/
cp server/package.json ../vendor/server/
cp server/package-lock.json ../vendor/server/
cp server/out/server.js ../vendor/server/
cp server/out/constants.js ../vendor/server/
cp server/out/utils.js ../vendor/server/
cd ..
npm run postinstall
