#!/bin/bash

set -e

VERSION="1.1.1"

TMP_DIR="_tmp"
DEST_DIR="vendor"
VSCODE_EXT="rescript-vscode-$VERSION.vsix"

rm -rf $TMP_DIR || true
rm -rf $DEST_DIR || true

mkdir -p $DEST_DIR

mkdir $TMP_DIR \
&& wget -q --show-progress --output-document=$TMP_DIR/$VSCODE_EXT https://github.com/rescript-lang/rescript-vscode/releases/download/$VERSION/$VSCODE_EXT \
&& tar -xf $TMP_DIR/$VSCODE_EXT -C $TMP_DIR \
&& cp -R $TMP_DIR/extension/package.json $DEST_DIR/ \
&& cp -R $TMP_DIR/extension/server $DEST_DIR/ \
&& rm -rf $DEST_DIR/server/node_modules \
&& rm -rf $TMP_DIR

# postinstall
cd vendor && npm install --only=prod --ignore-scripts && cd server && npm install --only=prod
